export const AUDIT_ACTION_TYPES = [
  "CREATE_EXPENSE",
  "UPDATE_EXPENSE",
  "DELETE_EXPENSE",
  "CREATE_USER",
  "RESEND_INVITE",
  "CREATE_SETTLEMENT",
  "NUDGE_SENT",
  "ADD_EXPENSE_COMMENT",
  "TOGGLE_EXPENSE_REACTION",
  "ACCESS_DENIED",
  "VALIDATION_FAILED",
  "ACTION_FAILED",
  "RESET_MONTH",
  "LOGIN",
  "COMPLETE_ONBOARDING",
  "UPDATE_HOUSE",
  "UPDATE_BUDGET",
  "UPDATE_USER",
  "DELETE_USER",
] as const;

export type AuditActionType = (typeof AUDIT_ACTION_TYPES)[number];
